# Site settings
author: Michael Rabon
title: "Software Engineering : A Path to Success"
header-img: img/home-bg.png
email: nobar86@gmail.com
copyright_name: Michael Rabon
description: > # this means to ignore newlines until "baseurl:"
  Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nobar86

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
